common:
  path_to_csv: ./results
  max_width: 1920
  max_height: 1080
  pool_size: 2
  headless: true


scrapers:
  Q2S:
    human_name: Quotes to Scrape
    name: q2s
    url: https://quotes.toscrape.com
    pool_size: 5