common:
  path_to_csv: ./results
  max_width: 1920
  max_height: 1080
  pool_size: 2
  headless: false


scrapers:
  SomeWebsiteScraperExample:
    human_name: Some website
    name: some_website
    url: https://some_website.com
    scraper: DummiesScraper
    # scraper: some_website_emplemantation_label
    # pool_size: 10
    # proxy:
    #   server: "http://proxy:8080"
    #   username: "user"
    #   password: "pass"